language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction

notifications:
  slack: 50shadesofsnow:wm4DseU6q44Sb1tec1kvVbav