language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction

script: phpunit --configuration tests/phpunit.xml

#after_script:
#  - phpmetrics ./src

notifications:
  slack: 50shadesofsnow:wm4DseU6q44Sb1tec1kvVbav
